rm(list = ls())

# ---- INTRODUCTION -------------------------------------------------------------- #

# So far you've seen R Markdown used to produce HTML documents.
# This chapter gives a brief overview of some of the many other types
# of output you can produce with R Markdown. There are two ways to
# set the output of a document:

  # 1. Permanently, by modifying the the YAML header:
#      title: "Viridis Demo"
#      output: html_document


  # 2. Transiently, by calling rmarkdown::render() by hand:
rmarkdown::render(
  "diamond-sizes.Rmd",
  output_format = "word_document"
)

# This is useful if you want to programmatically produce multiple
# types of output.

# RStudio's knit button renders a file to the first format listed in its
# output field. You can render to additional formats by clicking the
# drop-down menu beside the knit button.





# ---- OUTPUT OPTIONS ------------------------------------------------------------ #

# Each output format is associated with an R function. You can either
# write foo or pkg::foo. If you omit pkg, the default is assumed to be
# rmarkdown. It's important to know the name of the function that
# makes the output because that's where you get help. For example, to
# figure out what parameters you can set with html_document, look
# at ?rmarkdown:html_document().

# To override the default parameter values, you need to use an expan-
# ded output field. For example, if you wanted to render an
# html_document with a floating table of contents, you'd use:
#          output:
#            html_document:
#            toc: true
#          toc_float: true


# You can even render to multiple outputs by supplying a list of formats:
#          output:
#          html_document:
#          toc: true
#        toc_float: true
#        pdf_document: default

# Note the special syntax if you don't want to override any of the default options.






# ---- DOCUMENTS ------------------------------------------------------------------ #

# The previous chapter focused on the default html_document output.
# There are number of basic variations on that theme, generating dif-
# ferent types of documents:
  # pdf_document makes a PDF with LaTeX (an open source docu-
  # ment layout system), which you'll need to install. RStudio will
  # prompt you if you don't already have it.

  # word_document for Microsoft Word documents (.docx).

  # odt_document for OpenDocument Text documents (.odt)

  # rtf_document for Rich Text Format (.rtf) documents

  # md_document for a Markdown document. This isn't typically
  # useful by itself, but you might use it if, for example, your corpo-
  # rate CMS or lab wiki uses Markdown.

  # github_document is a tailored version of md_document designed
  # for sharing on GitHub.

# Remember, when generating a document to share with decision
# makers, you can turn off the default display of code by setting global
# options in the setup chunk:

knitr::opts_chunk$set(echo = FALSE)

# For html_documents another option is to make the code chunks hid-
# den by default, but visible with a click:
#  output:
#   html_document:
#     code_folding: hide







# ---- NOTEBOOKS --------------------------------------------------------------------- #

# A notebook, html_notebook, is a variation on an html_document.
# The rendered outputs are very similar, but the purpose is different.
# An html_document is focused on communicating with decision
# makers, while a notebook is focused on collaborating with other
# data scientists. These different purposes lead to using the HTML
# output in different ways. Both HTML outputs will contain the fully
# rendered output, but the notebook also contains the full source
# code. That means you can use the .nb.html generated by the note-
# book in two ways:

  # You can view it in a web browser, and see the rendered output.
  # Unlike html_document, this rendering always includes an
  # embedded copy of the source code that generated it.

  # You can edit it in RStudio. When you open an .nb.html file,
  # RStudio will automatically re-create the .Rmd file that generated
  # it. In the future, you can also include supporting files (e.g., .csv
  # data files), which will be automatically extracted when needed.

# Emailing .nb.html files is a simple way to share analyses with your
# colleagues. But things will get painful as soon as they want to make
# changes. If this starts to happen, it's a good time to learn Git and
# GitHub. Learning Git and GitHub is definitely painful at first, but
# the collaboration payoff is huge. As mentioned earlier, Git and Git-
# Hub are outside the scope of the book, but there's one tip that's use-
# ful if you're already using them: use both html_notebook and
# github_document outputs:

# output:
#   html_notebook: default
#   github_document: default

# html_notebook gives you a local preview, and a file that you can
# share via email. github_document creates a minimal MD file that
# you can check into Git. You can easily see how the results of your
# analysis (not just the code) change over time, and GitHub will ren-
# der it for you nicely online.







# ---- PRESENTATIONS ----------------------------------------------------------- #

# You can also use R Markdown to produce presentations. You get less
# visual control than with a tool like Keynote or PowerPoint, but auto-
# matically inserting the results of your R code into a presentation can
# save a huge amount of time. Presentations work by dividing your
# content into slides, with a new slide beginning at each first (#) or
# second (##) level header. You can also insert a horizontal rule (***)
# to create a new slide without a header.

# R Markdown comes with three presentations formats built in:

# ioslides_presentation
# HTML presentation with ioslides.

# slidy_presentation
# HTML presentation with W3C Slidy.

# beamer_presentation
# PDF presentation with LaTeX Beamer.

# Two other popular formats are provided by packages:
  # revealjs::revealjs_presentation
  # HTML presentation with reveal.js. Requires the revealjs package.
  # rmdshower
  # Provides a wrapper around the shower presentation engine.






# ---- DASHBOARDS ---------------------------------------------------------------- #

# Dashboards are a useful way to communicate large amounts of
# information visually and quickly. €exdashboard makes it particu-
# larly easy to create dashboards using R Markdown and a convention
# for how the headers affect the layout:

  # 1. Each level 1 header (#) begins a new page in the dashboard.
  # 2. Each level 2 header (##) begins a new column.
  # 3. Each level 3 header (###) begins a new row.

# flexdashboard also provides simple tools for creating sidebars, tab-
# sets, value boxes, and gauges. To learn more about flexdashboard
# visit http://rmarkdown.rstudio.com/flexdashboard/.







# ---- INTERACTIVITY --------------------------------------------------------------- #

# Any HTML format (document, notebook, presentation, or dash-
# board) can contain interactive components.

# htmlwidgets
# HTML is an interactive format, and you can take advantage of that
# interactivity with htmlwidgets, R functions that produce interactive
# HTML visualizations. For example, take the following leaflet map. If
# you're viewing this page on the web, you can drag the map around,
# zoom in and out, etc. You obviously can't do that on a book, so
# rmarkdown automatically inserts a static screenshot for you:

#install.packages("leaflet")

library(leaflet)
leaflet() %>%
  setView(174.764, -36.877, zoom = 16) %>%
  addTiles() %>%
  addMarkers(174.764, -36.877, popup = "Maungawhau")

# The great thing about htmlwidgets is that you don't need to know
# anything about HTML or JavaScript to use them. All the details are
# wrapped inside the package, so you don't need to worry about it.
# There are many packages that provide htmlwidgets, including:

  # dygraphs for interactive time series visualizations.
  # DT for interactive tables.
  # rthreejs for interactive 3D plots.
  # DiagrammeR for diagrams (like flow charts and simple nodelink diagrams).

# To learn more about htmlwidgets and see a more complete list of
# packages that provide them, visit http://www.htmlwidgets.org/.






# ---- SHINY ---------------------------------------------------------------------- #

# htmlwidgets provide client-side interactivity-all the interactivity
# happens in the browser, independently of R. On one hand, that's
# great because you can distribute the HTML file without any connec-
# tion to R. However, that fundamentally limits what you can do to
# things that have been implemented in HTML and JavaScript. An
# alternative approach is to use Shiny, a package that allows you to
# create interactivity using R code, not JavaScript.

# To call Shiny code from an R Markdown document, add runtime:
# shiny to the header. (see RMarkdown document)










# ---- WEBSITES ------------------------------------------------------------------- #

# With a little additional infrastructure you can use R Markdown to
# generate a complete website:

  # Put your .Rmd files in a single directory. index.Rmd will become
  # the home page.

  # Add a YAML file named _site.yml that provides the navigation
  # for the site. For example:

#name: "my-website"
#navbar:
#  title: "My Website"
#left:
#  - text: "Home"
#href: index.html
#- text: "Viridis Colors"
#href: 1-example.html
#- text: "Terrain Colors"
#href: 3-inline.html

# Execute rmarkdown::render_site() to build _site, a directory of
# files ready to deploy as a standalone static website, or if you use an
# RStudio Project for your website directory. RStudio will add a Build
# tab to the IDE that you can use to build and preview your site.

# Read more at http://bit.ly/RMarkdownWebsites.







# ---- OTHER FORMATS ------------------------------------------------------------ #

# Other packages provide even more output formats:

# The bookdown package makes it easy to write books, like this
# one. To learn more, read Authoring Books with R Markdown, by
# Yihui Xie, which is, of course, written in bookdown. Visit http://
# www.bookdown.org to see other bookdown books written by the
# wider R community

# The prettydoc package provides lightweight document formats
# with a range of attractive themes.

# The rticles package compiles a selection of formats tailored for
# specific scientific journals.

# See http://rmarkdown.rstudio.com/formats.html for a list of even
# more formats. You can also create your own by following the
# instructions at http://bit.ly/CreatingNewFormats.






# ---- LEARNING MORE ------------------------------------------------------------- #

# To learn more about effective communication in these different for
# mats I recommend the following resources:

# To improve your presentation skills, I recommend Presentation
# Patterns by Neal Ford, Matthew McCollough, and Nathaniel
# Schutta. It provides a set of effective patterns (both low- and
# high-level) that you can apply to improve your presentations.

# If you give academic talks, I recommend reading the Leek group
# guide to giving talks.

# I haven't taken it myself, but I've heard good things about Matt
# McGarrity's online course on public speaking.

# If you are creating a lot of dashboards, make sure to read Ste-
# phen Few's Information Dashboard Design: Te E???ective Visual
# Communication of Data. It will help you create dashboards that
# are truly useful, not just pretty to look at.

# Effectively communicating your ideas often benefits from some
# knowledge of graphic design. Te Non-Designer's Design Book is
# a great place to start.

